# Use official Python 3.13 image as base
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Ensure entrypoint script has correct permissions
RUN chmod 755 /app/entrypoint.sh

# Expose port for Django development server
EXPOSE 8000

# Set entrypoint
ENTRYPOINT ["sh", "/app/entrypoint.sh"]
